### ISSUE TITLE
Skipping Calendar folder?

### ISSUE THREAD

**Issue by iDGS** [mwesten/Plugin-Sitemap#3]
This thing is perfect!  Er, almost...?  (Or maybe I'm not understanding something?)

For instance,

> It finds: `/5-journal/2012-11-15-website-make-over.md`
> yet
> it skips: `/4-calendar/2013-07-04-independence-day.md`

And by find and skip, I mean likewise for all contents of the relevant folders.  That is, although I can't see why, it finds and records all entries in the blog, or "journal" folder--writing them to the sitemap file as it should--but completely skips over all contents of the "calendar" folder.

I note that another sitemap generator ([https://github.com/ericbarnes/statamic-sitemap](https://github.com/ericbarnes/statamic-sitemap)) did likewise, so I suspect the problem could very well be with me.  ...Except I just can't figure out what it is.  (Got any hints?)

**Comment by mwesten** [comment]
Closing this issue.
Statamic v1 is unsupported and this repo will be archived.
