### ISSUE TITLE
Included sitemap as page.md within /sitemap folder

### ISSUE THREAD

**Issue by mxjrdn** [mwesten/Plugin-Sitemap#4]
Thanks for writing this plugin, it's saved me a bunch of time. 

I'm just making note of when I installed the plugin (on v1.6.2, for what it's worth) adding `sitemap.xml.md` didn't work, but changing the page name to `page.md` and then creating a new folder title `sitemap` worked just fine and created the expected result (the final functioning file path was `sitemap/page.md`). 

Unfortunately I don't have any idea why or how this happened. I'm pretty new to the Statamic ecosystem and I'm not sure of anything beyond guessing that maybe v1.6 handles page urls slightly differently. I'm just making note of the issue for future generations.

**Comment by mwesten** [comment]
Closing this issue.
Statamic v1 is unsupported and this repo will be archived.
