### ISSUE TITLE
Priority setting ignored

### ISSUE THREAD

**Issue by raddevon** [mwesten/Plugin-Sitemap#5]
It seems the plugin is ignoring my priority setting. I have set the priority for my portfolio page to 0.9, but the sitemap still shows it as the default 0.5. Here's the YAML front matter for that page which is `/_content/1.portfolio/page.md`:

```

---
title: Portfolio
_template: portfolio
_default_folder_template: project
priority: 0.9

---
```

Here's the output for that page in the sitemap:

```
<url>
  <loc>http://raddevon.com/portfolio</loc>
  <lastmod>2013-10-31</lastmod>
  <changefreq>yearly</changefreq>
  <priority>0.5</priority>
</url>
```

**Comment by mwesten** [comment]
Closing this (unresolved)issue.
Statamic v1 is unsupported and this repo will be archived.
